1337b04rd project
alem-platform/backend pull request #3
Opened 2024-12-02 10:59 UTC by savvax

2024-12-23 23:29 UTC, msarvaro reviewed
в целом вообще классно, добавить больше то и нечего

2024-12-23 23:29 UTC, msarvaro commented on 1337b04rd/README.md
> +#### Session Management
я бы добавил больше интересных статей про уязвимости куки, мне было бы интересно прочитать о них прочитать, если бы делал этот проект

например - https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies

2024-12-23 23:29 UTC, msarvaro commented on 1337b04rd/README.md
> +### Testing
может оставить ссылку/ссылки на полезные статьи по тестингу? от самой гошки классная статья маленькая (https://go.dev/doc/tutorial/add-a-test)

2024-12-30 05:08 UTC, atlekbai requested changes

2024-12-30 05:08 UTC, atlekbai commented on 1337b04rd/README.md
> +  - Posts with comments are deleted 15 minutes after the last comment.
Получается студентам нужно будет ранить на фоне горутину, которая периодично чекает такие посты?

2024-12-30 05:08 UTC, atlekbai commented on 1337b04rd/README.md
> +  - Each user is assigned a unique avatar and name (name can be changed) from The Rick and Morty AP, identified via cookies.
```suggestion
  - Each user is assigned a unique avatar and name (name can be changed) from The Rick and Morty API, identified via cookies.
```

2025-01-06 02:55 UTC, savvax commented on 1337b04rd/README.md
> +  - Posts with comments are deleted 15 minutes after the last comment.
Да, использование тикера кажется наиболее привлекательным вариантом.

2025-01-13 12:25 UTC, saboopher approved these changes

2025-01-13 12:26 UTC, merged